#!/bin/sh

echo 'Restoring all the regular config files.'
sleep 4

stow -v -R bash
stow -v -R bin
stow -v -R compton
stow -v -R emacs
stow -v -R herbstluftwm
stow -v -R mutt
stow -v -R nitrogen
stow -v -R polybar
stow -v -R ranger
stow -v -R ssh
stow -v -R vifm
stow -v -R vim
stow -v -R xresources
stow -v -R zsh

echo 'Restoration completed.'

sed -i "s%	IdentityFile.*%	IdentityFile ~/.ssh/id_rsa_$(hostname)%g" ~/.ssh/config

echo 'SSH identity updated.'
