#!/bin/sh

# BSWPM config

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nitrogen --restore &
~/.config/polybar/launch.sh mainbar-herbst

# Workspaces
bspc monitor -d       ﭧ    

# Configuration
bspc config border_width  2
bspc config window_gap    16
bspc config split_ratio   0.5
