#!/bin/sh

# BSWPM config

# Autostart
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd -c $XDG_CONFIG_HOME/sxhkd/common_sxhkdrc $XDG_CONFIG_HOME/sxhkd/bspwm_sxhkdrc &
picom &
feh --no-fehbg --bg-scale "$HOME/Pictures/dark-leaves.jpg" &
$XDG_CONFIG_HOME/polybar/launch.sh mainbar-herbst &

# Workspaces
bspc monitor -d DEV DOCKER SYS DOC WWW TEST MEDIA VMAN HOMELAB

# Configuration
bspc config border_width  2
bspc config split_ratio   0.5
bspc config top_padding   20
bspc config window_gap    5

bspc config normal_border_color '#565656'
bspc config active_border_color '#2aa198'
bspc config focused_border_color '#2aa198'
