version: '3.7'

services:
  transmission:
    image: linuxserver/transmission:3.00-r0-ls57
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=transmission #optional
      - PASS=transmission #optional
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
