#!/bin/sh

if [ -x "$(command -v node)" ] ; then
    "$XDG_CONFIG_HOME"/herbstluftwm/node/autostart.js
else
    "$XDG_CONFIG_HOME"/herbstluftwm/bash/autostart.sh
fi
# "$XDG_CONFIG_HOME"/herbstluftwm/python/autostart.py
